### ISSUE TITLE
Add support for relative/absolute/alias paths

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-cli#12]
- [ ] equinor/dm-cli#11 
- [x] equinor/dm-cli#10 
- [x] equinor/dm-cli#9 
- [x] equinor/data-modelling-storage-service#271 
- [ ] Versioning in TAG (need to be discussed)

**Comment by soofstad** [comment]
We will try and move all of these into the DMSS
