### ISSUE TITLE
refactor: support storage recipes

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-cli#97]
# Tasks

- [x] feat(dm-cli): update files on disk to DMSS @eoaksnes 
- [x] feat(dmss): add files endpoint that receives binary files and creates file entities with the binary data as content @eoaksnes 
- [x] refactor(dm-core-packages): make sure that it is possible to handle binary data type @eoaksnes 
- [x] feat(dm-core-packages): add file plugin to handle files @eoaksnes

**Comment by l3abak** [comment]
Here is the general spec. of the design. 

1- SotrageNonContained is specified in StorageRecipe. 
2- The attribute, which is StorageNoncontained True, is going to be replaced with an instance of the Reference with referenceType set to storage. 

Example: if 3Dmodel is StorageNonContained (Model Contained) in the Car.

```
Car = { type: ALIAS:/models/Car,
            name: "volvo",
            3dModel: { type: Reference
                               address: ALIAS:/3dmodels/volvo.3ds,
                               referenceType: Storage
                             }
}
```

**Comment by eoaksnes** [comment]
From today's meeting:

```
{
  "name": "Signal",
  "type": "CORE:Blueprint",
  "attributes": [
    {
      "attributeType": "number",
      "type": "CORE:BlueprintAttribute",
      "name": "data",
      "dimensions": "*"
    },
    {
      "attributeType": "File",
      "type": "CORE:BlueprintAttribute",
      "name": "plot"
    }
  ]
}
```

On disk:

```
{
  "type": "Signal",
  "data": {
    "type": "Reference",
    "address": "./LargeArrayOfNumbers",
    "referenceType": "Storage"
  },
  "plot": {
    "type": "Reference",
    "address": "./file.pdf",
    "referenceType": "Storage"
  }
}
```

On Mongo:

```
{
  "type": "Signal",
  "data": {
    "type": "Reference",
    "address": "./LargeArrayOfNumbers",
    "referenceType": "Storage"
  },
  "plot": {
    "type": "Reference",
    "address": "./DS/$1234",
    "referenceType": "Storage"
  }
}
```
The plot points to this wrapper that is created on import:

```
{
  "_id": $1234,
  "type": File
  "name": "file.pdf",
  "author" "someone",
  "date": "01/01/20",
  "size": "1G",
  "filetype": "pdf",
  "data": {
    "type": "Reference",
    "address": "DS/$ID",
    "referenceType": "Storage"
  },
  "data": {
    "type": "AzureBlob",
    "address": "$ID"
  },
  "data": {
    "type": "DTO",
    "data": b"binarystuff"
  }
}
```

NOTE: We need to take a decision on if the data attribute should use the generic reference or be more specific. 

The LargeArrayOfNumbers on disk can look like this:

```

[1,2,3,4,5,6]
```

And on Mongo:

```
<TODO>
```

**Comment by soofstad** [comment]
After discussion on 24-26.5 these things were concluded:
- "StorageItemTechWrapper" (whats inside lookup table) today, will be kept as is. __But__ might be refactored to include a type (be a proper entity defined by a Blueprint) and stored as a separate document within the DMSS internal structure
-  Should be possible to store binary data in mongo. This Means that the MongoRepository Plugin must encode/decode binary. Not decided when we want to implement this.
- Primary primitive types can NOT be stored uncontained (No need to DTO)
- The autogenerated "File" meta-information wrapper is optional (in concept), but will always be created when importing with dm-cli

Not decided:
- When should the get/upload_blob endpoints be used for binary data?
- As the concept is defined today, it does not include these endpoints, meaning the binary data would always be included directly in the "get_document" json document.

**Comment by eoaksnes** [comment]
-----


Tasks

 - [ ] import lookup table before import data. Need to update so that dm cli run commands in the correct order 1) add blueprints 2) create lookup 3) add data
 - [ ] update dm-cli to use normal references for all non-storage attributes (both JSON and binary)
 - [ ] create wrapper in DMSS when things are uploaded (DTOs for uncontained non binary type etc)

Import needs to use storage recipes. 

Alternative 1: create a single command that is smart so it will 1) add blueprints before 2) creating a lookup table and  3) adding the data
Alternative 2: be very strict on folder structure and run commands in the correct order 1) add blueprints 2) create lookup 3) add data.

Go for alternative 2 in the short term, but in the long term go for alternative 1. 

Note that for alternative 1 we need to make the upload smarter so that it does not delete packages and files when it tries to upload already uploaded packages.

For alternative 2 dm reset app add config file that contains list of blueprints, entities, and recipes to upload. Either single list or splitter up into several lists.

## Acceptance test: try to upload large array of numbers 

```
Type: BlueprintA
data: {
   type: Reference
   address: ALIAS:/PATH/LargeArrayOfNumbers
   referenceType: Storage
}
```

The large array of numbers:
```
[0,1,2,3,...x]
```

```
StorageRecipe
data: uncontained
```

When the entity 

## Acceptance test: try to upload of binary file

Use a reference for all non-storage attributes:

```
{
  type: Reference
  address: ALIAS:/PATH/drawFile
  referenceType: Storage
}
```

Need to look at what it is pointing at to find out more information.

```
{
  type:  File (on disc) AzureBlob (in Azure)
  address: Place to file on a disc or id for blob in Mongo
}
```

Need to create storage specific documents (wrappers) when import in to dmss from disc.
